name: mystore
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  provider:
  bottom_navy_bar: ^6.0.0
  firebase_core: "any"
  firebase_auth: "any"
  firebase_database: "any"
  cloud_firestore: ^0.14.2
  firebase_storage: "any"
  google_sign_in: "^4.5.1"
  cached_network_image:
  shared_preferences: ^0.5.12+4
  flutter_launcher_icons: 0.7.5
  sliding_up_panel: ^1.0.2
  wakelock: ^0.1.4+1
  permission_handler: ^3.0.0
  url_launcher: ^5.7.10
  font_awesome_flutter: 8.8.1
  gradient_text: 1.0.2
  image_picker: ^0.6.7+12
  flare_flutter:
  random_color: ^1.0.5
  ff_navigation_bar:
  responsive_builder: ^0.2.0+2
  marquee: ^1.5.2
  camera: ^0.5.8+2
  carousel_slider: ^2.2.1
  stacked_services: 0.5.4+3
  get_it: ^5.0.0
  stacked: ^1.7.6
  path_provider: ^1.1.0
  path: ^1.6.2
  esys_flutter_share: ^1.0.2
  open_file: ^3.0.1
  line_icons:
  flutter_svg:
  intl: 0.16.1
  date_range_picker: ^1.0.5
  auto_size_text: ^2.0.2
  flutter_spinkit: ^3.1.0
  flutter_auth_buttons: ^0.5.0
  dio: ^3.0.10
  uuid: 2.0.1
  timeago: ^2.0.28
  like_button: ^1.0.4
  image_cropper: ^1.3.1
  flutter_icons: ^1.1.0
  percent_indicator: ^2.1.8
  fluttertoast: ^7.1.1
  animations: ^1.1.2
  image: ^2.1.18
  google_fonts: ^1.1.1
  modal_progress_hud: ^0.1.3
  flutter_facebook_auth: ^2.0.2
  flutter_facebook_login: ^3.0.0
  screen: ^0.0.5 # keeping screen on
  pie_chart: ^5.0.0
  rxdart: ^0.25.0
  cupertino_icons: ^1.0.2
  charts_flutter: ^0.10.0
  lite_rolling_switch: ^0.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

fonts:
  fonts:
    - asset: assets/fonts/Lato-Regular.ttf
    - asset: assets/fonts/Lato-Black.ttf
    - asset: assets/fonts/Lato-Bold.ttf
      weight: 700
    - asset: assets/fonts/Lato-Light.ttf
      weight: 300
    - asset: assets/fonts/Lato-Thin.ttf
